<?php
/*
 * hook_menu()
 */
function unlimitedfield_remove_menu(){
  $items = array();
  $items['admin/config/unlimitedfield_remove'] = array(
    'title' => t('UnlimitedField Remove Settings'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('unlimitedfield_remove_admin_form'),
    'access arguments' => array('administer modules'),
    'type' => MENU_NORMAL_ITEM,
  );
  
  return $items;
}
/*
 * hook_field_widget_form_alter()
 */
function unlimitedfield_remove_field_widget_form_alter(&$element, &$form_state, $context)
{
  // some elements are buried, so we have to look for them
  $found = false;
  
  if(isset($element['#field_name'])){
    $details = $element;
    $found = true;
  } else {
    // look deeper
    foreach($element as $key => $value){
      if(isset($value['#field_name'])){
        $found = true;
        $details = $value;
        break;
      }
    }
  }
  
  // make sure we want to apply changes to this field
  if($found && variable_get('unlimitedfield_remove_'.$details['#field_name'],0) == 1)
  {
    // add our js
    drupal_add_js(drupal_get_path('module','unlimitedfield_remove').'/unlimitedfield_remove.js');
    
    // add our remove link
    $remove_button = array(
      '#name' => $details['#field_name'].'_'.$details['#delta'].'_remove_button',
      '#type' => 'markup',
      '#value' => t('Remove'),
      '#validate' => array(),
      '#markup' => '<div class="unlimitedfield_remove_button">Remove</div>',
      '#weight' => -99,
    );
    
    $element['remove_button'] = $remove_button;
  }
}
/*
 * Admin settings form
 */
function unlimitedfield_remove_admin_form($form, &$form_state){
  $fields = field_info_fields();
  
  $form['description'] = array(
    '#markup' => '<div class="description">Check each unlimited field you would like to add a Remove button to.</div>',
  );
  
  foreach($fields as $key => $field){
    if($field['cardinality'] == -1){
      $form[$key] = array(
        '#type' => 'checkbox',
        '#title' => $key,
        '#default_value' => variable_get('unlimitedfield_remove_'.$key, 0),
      );
    }
  }
  
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save Settings'),
  );
  
  return $form;
}
/*
 * Submit functon for our settings form
 */
function unlimitedfield_remove_admin_form_submit($form, &$form_state){
  foreach($form_state['values'] as $key => $value){
    if($value == 1 || $value == 0){
      variable_set('unlimitedfield_remove_'.$key, $value);
    }
  }
  drupal_set_message('Your settings have been saved.', 'status');
}