<?php

/**
 * Implements hook_views_api().
 */
function osn_views_api() {
  return array(
    'api' => 3.0,
    'path' => drupal_get_path('module', 'osn'),
  );
}

function osn_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'event_node_form') {
    $form['field_link']['und']['add_more']['#value'] = 'Add another weblink';
    $form['field_event_date']['und']['add_more']['#value'] = 'Add another date';
  }
  
  if ($form_id == 'user_register_form') {
    asort($form['group_audience']['und']['#options']);
  	$form['group_audience']['und']['#title'] = 'Group organisation';
  }
  if ($form_id == 'event_node_form' && !empty($form['group_audience'])) {
  	if (isset($form['group_audience']['und']['#options']['Other groups'])) {
      asort($form['group_audience']['und']['#options']['Other groups']);
  	}
    if (isset($form['group_audience']['und']['#options']['My groups'])) {
      asort($form['group_audience']['und']['#options']['My groups']);
    }
    $form['group_audience']['und']['#title'] = 'Group organisation';
  }
  if ($form_id == 'organisation_node_form') {
  	unset($form['group_group']);
  	$form['field_link']['und']['add_more']['#value'] = 'Add another weblink';
  }
}

// This sets the membership to pending after a user registers for an organisation.
function osn_og_membership_insert($og_membership) {
  db_update('og_membership') // Table name no longer needs {}
      ->fields(array(
        'state' => '2',
    ))
      ->condition('id', $og_membership->id)
      ->execute();
}

function osn_user_view($account, $view_mode, $langcode) {
  $my_orgs = views_embed_view('og_user_groups');
  $account->content['summary']['organisations'] =  array(
    '#title' => '',
    '#type' => 'user_profile_item',
    '#markup' => $my_orgs,
  );
}





